CREATE TABLE TWITTER_USER
(
      userId INTEGER PRIMARY KEY AUTO_INCREMENT
    , nickname VARCHAR(25)
    , login VARCHAR(25) NOT NULL UNIQUE
    , dateRegistered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , dateOfBirth DATE
    , about VARCHAR(250)
);

--NEXT--

CREATE TABLE TWEET
(
      tweetId INTEGER PRIMARY KEY AUTO_INCREMENT
    , userId INTEGER NOT NULL
    , referenceTweet INTEGER
    , datePosted TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , content VARCHAR(250) NOT NULL
    , FOREIGN KEY (userId) REFERENCES TWITTER_USER(userId)
);

--NEXT--

CREATE TABLE FOLLOWERS
(
      userId INTEGER NOT NULL
    , followingUserId INTEGER NOT NULL
    , since TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CONSTRAINT UNIQUE_USER_ID_FOLLOWER_ID UNIQUE (userId, followingUserId)
);

--NEXT--

CREATE TABLE LIKES
(
      tweetId INTEGER NOT NULL
    , likedUserId INTEGER NOT NULL
    , likedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , CONSTRAINT UNIQUE_TWEET_ID_USER_LIKED_ID UNIQUE (tweetId, likedUserId)
);

--NEXT--

CREATE TABLE USER_AUTHENTICATION
(
      login VARCHAR(25) NOT NULL UNIQUE
    , salted BLOB NOT NULL
    , saltedPassword BLOB NOT NULL
    , FOREIGN KEY(login) REFERENCES TWITTER_USER(login)
);

--NEXT--

CREATE TABLE SESSION
(
      sessionId INTEGER PRIMARY KEY AUTO_INCREMENT
    , login VARCHAR(25) NOT NULL
    , started TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    , ended TIMESTAMP
);
